package com.yucheng.cmis.batch.diffdb.pojo;

import java.math.BigDecimal;

public class BatPospTCheckResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.EVENTID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String eventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TRAN_PLACE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTranPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TRAN_PLACE2
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTranPlace2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_INST_ID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_BATCH_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saBatchDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_HOST_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saHostDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SETTLE_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSettleDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SYS_TRA_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSysTraNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_RTR_REF_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saRtrRefNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TXN_DATE_TIME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTxnDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_MCHT_CD
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saMchtCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TERM_ID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_PRI_ACCT_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saPriAcctNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SELF_FLG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSelfFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_MSG_TYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saMsgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_PROC_CODE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saProcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_POS_CON_CD
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saPosConCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_BALACCT_STATUS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saBalacctStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SETTLE_STATUS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSettleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_ISS_BRC
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saIssBrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_ACQ_BRC
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saAcqBrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_CANCL_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saCanclFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_ACQ_INS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saAcqIns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_FWD_INS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saFwdIns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_CD_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saCdFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_ERR_DATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saErrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_HOST_SERIAL
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saHostSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_BALERR_SERIAL
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saBalerrSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_UPDATETIME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TELLERCODE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTellercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TRAN_PLACE3
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTranPlace3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TRANDEVTYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTrandevtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TRANKIND
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saTrankind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_CARDTRANTYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saCardtrantype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_T0_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saT0Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.I_CMP_NO
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private Integer iCmpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_TXN_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saTxnAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_CHARGE_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saChargeFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_PAY_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saPayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_MERCH_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saMerchFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SELF_MERC_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saSelfMercFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_CUSTOMER_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saCustomerFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.D_ERR_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal dErrAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.C_ERR_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal cErrAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_ACQ_BRC_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saAcqBrcFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.D_FEE_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal dFeeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.C_FEE_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal cFeeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SAV1
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saSav1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SAV2
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private BigDecimal saSav2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SAV3
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSav3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SAV4
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSav4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_SAV5
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saSav5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.SA_FRNT_DATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String saFrntDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.ETLNAME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String etlname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_posp_t_check_result.DATADATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    private String datadate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.EVENTID
     *
     * @return the value of bat_posp_t_check_result.EVENTID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.EVENTID
     *
     * @param eventid the value for bat_posp_t_check_result.EVENTID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setEventid(String eventid) {
        this.eventid = eventid == null ? null : eventid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TRAN_PLACE
     *
     * @return the value of bat_posp_t_check_result.SA_TRAN_PLACE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTranPlace() {
        return saTranPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TRAN_PLACE
     *
     * @param saTranPlace the value for bat_posp_t_check_result.SA_TRAN_PLACE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTranPlace(String saTranPlace) {
        this.saTranPlace = saTranPlace == null ? null : saTranPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TRAN_PLACE2
     *
     * @return the value of bat_posp_t_check_result.SA_TRAN_PLACE2
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTranPlace2() {
        return saTranPlace2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TRAN_PLACE2
     *
     * @param saTranPlace2 the value for bat_posp_t_check_result.SA_TRAN_PLACE2
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTranPlace2(String saTranPlace2) {
        this.saTranPlace2 = saTranPlace2 == null ? null : saTranPlace2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_INST_ID
     *
     * @return the value of bat_posp_t_check_result.SA_INST_ID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaInstId() {
        return saInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_INST_ID
     *
     * @param saInstId the value for bat_posp_t_check_result.SA_INST_ID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaInstId(String saInstId) {
        this.saInstId = saInstId == null ? null : saInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_BATCH_DAY
     *
     * @return the value of bat_posp_t_check_result.SA_BATCH_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaBatchDay() {
        return saBatchDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_BATCH_DAY
     *
     * @param saBatchDay the value for bat_posp_t_check_result.SA_BATCH_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaBatchDay(String saBatchDay) {
        this.saBatchDay = saBatchDay == null ? null : saBatchDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_HOST_DAY
     *
     * @return the value of bat_posp_t_check_result.SA_HOST_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaHostDay() {
        return saHostDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_HOST_DAY
     *
     * @param saHostDay the value for bat_posp_t_check_result.SA_HOST_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaHostDay(String saHostDay) {
        this.saHostDay = saHostDay == null ? null : saHostDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SETTLE_DAY
     *
     * @return the value of bat_posp_t_check_result.SA_SETTLE_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSettleDay() {
        return saSettleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SETTLE_DAY
     *
     * @param saSettleDay the value for bat_posp_t_check_result.SA_SETTLE_DAY
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSettleDay(String saSettleDay) {
        this.saSettleDay = saSettleDay == null ? null : saSettleDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SYS_TRA_NUM
     *
     * @return the value of bat_posp_t_check_result.SA_SYS_TRA_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSysTraNum() {
        return saSysTraNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SYS_TRA_NUM
     *
     * @param saSysTraNum the value for bat_posp_t_check_result.SA_SYS_TRA_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSysTraNum(String saSysTraNum) {
        this.saSysTraNum = saSysTraNum == null ? null : saSysTraNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_RTR_REF_NUM
     *
     * @return the value of bat_posp_t_check_result.SA_RTR_REF_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaRtrRefNum() {
        return saRtrRefNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_RTR_REF_NUM
     *
     * @param saRtrRefNum the value for bat_posp_t_check_result.SA_RTR_REF_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaRtrRefNum(String saRtrRefNum) {
        this.saRtrRefNum = saRtrRefNum == null ? null : saRtrRefNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TXN_DATE_TIME
     *
     * @return the value of bat_posp_t_check_result.SA_TXN_DATE_TIME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTxnDateTime() {
        return saTxnDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TXN_DATE_TIME
     *
     * @param saTxnDateTime the value for bat_posp_t_check_result.SA_TXN_DATE_TIME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTxnDateTime(String saTxnDateTime) {
        this.saTxnDateTime = saTxnDateTime == null ? null : saTxnDateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_MCHT_CD
     *
     * @return the value of bat_posp_t_check_result.SA_MCHT_CD
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaMchtCd() {
        return saMchtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_MCHT_CD
     *
     * @param saMchtCd the value for bat_posp_t_check_result.SA_MCHT_CD
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaMchtCd(String saMchtCd) {
        this.saMchtCd = saMchtCd == null ? null : saMchtCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TERM_ID
     *
     * @return the value of bat_posp_t_check_result.SA_TERM_ID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTermId() {
        return saTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TERM_ID
     *
     * @param saTermId the value for bat_posp_t_check_result.SA_TERM_ID
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTermId(String saTermId) {
        this.saTermId = saTermId == null ? null : saTermId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_PRI_ACCT_NUM
     *
     * @return the value of bat_posp_t_check_result.SA_PRI_ACCT_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaPriAcctNum() {
        return saPriAcctNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_PRI_ACCT_NUM
     *
     * @param saPriAcctNum the value for bat_posp_t_check_result.SA_PRI_ACCT_NUM
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaPriAcctNum(String saPriAcctNum) {
        this.saPriAcctNum = saPriAcctNum == null ? null : saPriAcctNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SELF_FLG
     *
     * @return the value of bat_posp_t_check_result.SA_SELF_FLG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSelfFlg() {
        return saSelfFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SELF_FLG
     *
     * @param saSelfFlg the value for bat_posp_t_check_result.SA_SELF_FLG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSelfFlg(String saSelfFlg) {
        this.saSelfFlg = saSelfFlg == null ? null : saSelfFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_MSG_TYPE
     *
     * @return the value of bat_posp_t_check_result.SA_MSG_TYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaMsgType() {
        return saMsgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_MSG_TYPE
     *
     * @param saMsgType the value for bat_posp_t_check_result.SA_MSG_TYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaMsgType(String saMsgType) {
        this.saMsgType = saMsgType == null ? null : saMsgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_PROC_CODE
     *
     * @return the value of bat_posp_t_check_result.SA_PROC_CODE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaProcCode() {
        return saProcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_PROC_CODE
     *
     * @param saProcCode the value for bat_posp_t_check_result.SA_PROC_CODE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaProcCode(String saProcCode) {
        this.saProcCode = saProcCode == null ? null : saProcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_POS_CON_CD
     *
     * @return the value of bat_posp_t_check_result.SA_POS_CON_CD
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaPosConCd() {
        return saPosConCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_POS_CON_CD
     *
     * @param saPosConCd the value for bat_posp_t_check_result.SA_POS_CON_CD
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaPosConCd(String saPosConCd) {
        this.saPosConCd = saPosConCd == null ? null : saPosConCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_BALACCT_STATUS
     *
     * @return the value of bat_posp_t_check_result.SA_BALACCT_STATUS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaBalacctStatus() {
        return saBalacctStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_BALACCT_STATUS
     *
     * @param saBalacctStatus the value for bat_posp_t_check_result.SA_BALACCT_STATUS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaBalacctStatus(String saBalacctStatus) {
        this.saBalacctStatus = saBalacctStatus == null ? null : saBalacctStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SETTLE_STATUS
     *
     * @return the value of bat_posp_t_check_result.SA_SETTLE_STATUS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSettleStatus() {
        return saSettleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SETTLE_STATUS
     *
     * @param saSettleStatus the value for bat_posp_t_check_result.SA_SETTLE_STATUS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSettleStatus(String saSettleStatus) {
        this.saSettleStatus = saSettleStatus == null ? null : saSettleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_ISS_BRC
     *
     * @return the value of bat_posp_t_check_result.SA_ISS_BRC
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaIssBrc() {
        return saIssBrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_ISS_BRC
     *
     * @param saIssBrc the value for bat_posp_t_check_result.SA_ISS_BRC
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaIssBrc(String saIssBrc) {
        this.saIssBrc = saIssBrc == null ? null : saIssBrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_ACQ_BRC
     *
     * @return the value of bat_posp_t_check_result.SA_ACQ_BRC
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaAcqBrc() {
        return saAcqBrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_ACQ_BRC
     *
     * @param saAcqBrc the value for bat_posp_t_check_result.SA_ACQ_BRC
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaAcqBrc(String saAcqBrc) {
        this.saAcqBrc = saAcqBrc == null ? null : saAcqBrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_CANCL_FLAG
     *
     * @return the value of bat_posp_t_check_result.SA_CANCL_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaCanclFlag() {
        return saCanclFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_CANCL_FLAG
     *
     * @param saCanclFlag the value for bat_posp_t_check_result.SA_CANCL_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaCanclFlag(String saCanclFlag) {
        this.saCanclFlag = saCanclFlag == null ? null : saCanclFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_ACQ_INS
     *
     * @return the value of bat_posp_t_check_result.SA_ACQ_INS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaAcqIns() {
        return saAcqIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_ACQ_INS
     *
     * @param saAcqIns the value for bat_posp_t_check_result.SA_ACQ_INS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaAcqIns(String saAcqIns) {
        this.saAcqIns = saAcqIns == null ? null : saAcqIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_FWD_INS
     *
     * @return the value of bat_posp_t_check_result.SA_FWD_INS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaFwdIns() {
        return saFwdIns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_FWD_INS
     *
     * @param saFwdIns the value for bat_posp_t_check_result.SA_FWD_INS
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaFwdIns(String saFwdIns) {
        this.saFwdIns = saFwdIns == null ? null : saFwdIns.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_CD_FLAG
     *
     * @return the value of bat_posp_t_check_result.SA_CD_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaCdFlag() {
        return saCdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_CD_FLAG
     *
     * @param saCdFlag the value for bat_posp_t_check_result.SA_CD_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaCdFlag(String saCdFlag) {
        this.saCdFlag = saCdFlag == null ? null : saCdFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_ERR_DATE
     *
     * @return the value of bat_posp_t_check_result.SA_ERR_DATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaErrDate() {
        return saErrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_ERR_DATE
     *
     * @param saErrDate the value for bat_posp_t_check_result.SA_ERR_DATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaErrDate(String saErrDate) {
        this.saErrDate = saErrDate == null ? null : saErrDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_HOST_SERIAL
     *
     * @return the value of bat_posp_t_check_result.SA_HOST_SERIAL
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaHostSerial() {
        return saHostSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_HOST_SERIAL
     *
     * @param saHostSerial the value for bat_posp_t_check_result.SA_HOST_SERIAL
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaHostSerial(String saHostSerial) {
        this.saHostSerial = saHostSerial == null ? null : saHostSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_BALERR_SERIAL
     *
     * @return the value of bat_posp_t_check_result.SA_BALERR_SERIAL
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaBalerrSerial() {
        return saBalerrSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_BALERR_SERIAL
     *
     * @param saBalerrSerial the value for bat_posp_t_check_result.SA_BALERR_SERIAL
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaBalerrSerial(String saBalerrSerial) {
        this.saBalerrSerial = saBalerrSerial == null ? null : saBalerrSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_UPDATETIME
     *
     * @return the value of bat_posp_t_check_result.SA_UPDATETIME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaUpdatetime() {
        return saUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_UPDATETIME
     *
     * @param saUpdatetime the value for bat_posp_t_check_result.SA_UPDATETIME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaUpdatetime(String saUpdatetime) {
        this.saUpdatetime = saUpdatetime == null ? null : saUpdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TELLERCODE
     *
     * @return the value of bat_posp_t_check_result.SA_TELLERCODE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTellercode() {
        return saTellercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TELLERCODE
     *
     * @param saTellercode the value for bat_posp_t_check_result.SA_TELLERCODE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTellercode(String saTellercode) {
        this.saTellercode = saTellercode == null ? null : saTellercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TRAN_PLACE3
     *
     * @return the value of bat_posp_t_check_result.SA_TRAN_PLACE3
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTranPlace3() {
        return saTranPlace3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TRAN_PLACE3
     *
     * @param saTranPlace3 the value for bat_posp_t_check_result.SA_TRAN_PLACE3
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTranPlace3(String saTranPlace3) {
        this.saTranPlace3 = saTranPlace3 == null ? null : saTranPlace3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TRANDEVTYPE
     *
     * @return the value of bat_posp_t_check_result.SA_TRANDEVTYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTrandevtype() {
        return saTrandevtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TRANDEVTYPE
     *
     * @param saTrandevtype the value for bat_posp_t_check_result.SA_TRANDEVTYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTrandevtype(String saTrandevtype) {
        this.saTrandevtype = saTrandevtype == null ? null : saTrandevtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TRANKIND
     *
     * @return the value of bat_posp_t_check_result.SA_TRANKIND
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaTrankind() {
        return saTrankind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TRANKIND
     *
     * @param saTrankind the value for bat_posp_t_check_result.SA_TRANKIND
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTrankind(String saTrankind) {
        this.saTrankind = saTrankind == null ? null : saTrankind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_CARDTRANTYPE
     *
     * @return the value of bat_posp_t_check_result.SA_CARDTRANTYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaCardtrantype() {
        return saCardtrantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_CARDTRANTYPE
     *
     * @param saCardtrantype the value for bat_posp_t_check_result.SA_CARDTRANTYPE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaCardtrantype(String saCardtrantype) {
        this.saCardtrantype = saCardtrantype == null ? null : saCardtrantype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_T0_FLAG
     *
     * @return the value of bat_posp_t_check_result.SA_T0_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaT0Flag() {
        return saT0Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_T0_FLAG
     *
     * @param saT0Flag the value for bat_posp_t_check_result.SA_T0_FLAG
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaT0Flag(String saT0Flag) {
        this.saT0Flag = saT0Flag == null ? null : saT0Flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.I_CMP_NO
     *
     * @return the value of bat_posp_t_check_result.I_CMP_NO
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public Integer getiCmpNo() {
        return iCmpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.I_CMP_NO
     *
     * @param iCmpNo the value for bat_posp_t_check_result.I_CMP_NO
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setiCmpNo(Integer iCmpNo) {
        this.iCmpNo = iCmpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_TXN_AMOUNT
     *
     * @return the value of bat_posp_t_check_result.SA_TXN_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaTxnAmount() {
        return saTxnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_TXN_AMOUNT
     *
     * @param saTxnAmount the value for bat_posp_t_check_result.SA_TXN_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaTxnAmount(BigDecimal saTxnAmount) {
        this.saTxnAmount = saTxnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_CHARGE_FEE
     *
     * @return the value of bat_posp_t_check_result.SA_CHARGE_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaChargeFee() {
        return saChargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_CHARGE_FEE
     *
     * @param saChargeFee the value for bat_posp_t_check_result.SA_CHARGE_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaChargeFee(BigDecimal saChargeFee) {
        this.saChargeFee = saChargeFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_PAY_FEE
     *
     * @return the value of bat_posp_t_check_result.SA_PAY_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaPayFee() {
        return saPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_PAY_FEE
     *
     * @param saPayFee the value for bat_posp_t_check_result.SA_PAY_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaPayFee(BigDecimal saPayFee) {
        this.saPayFee = saPayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_MERCH_FEE
     *
     * @return the value of bat_posp_t_check_result.SA_MERCH_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaMerchFee() {
        return saMerchFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_MERCH_FEE
     *
     * @param saMerchFee the value for bat_posp_t_check_result.SA_MERCH_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaMerchFee(BigDecimal saMerchFee) {
        this.saMerchFee = saMerchFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SELF_MERC_FEE
     *
     * @return the value of bat_posp_t_check_result.SA_SELF_MERC_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaSelfMercFee() {
        return saSelfMercFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SELF_MERC_FEE
     *
     * @param saSelfMercFee the value for bat_posp_t_check_result.SA_SELF_MERC_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSelfMercFee(BigDecimal saSelfMercFee) {
        this.saSelfMercFee = saSelfMercFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_CUSTOMER_FEE
     *
     * @return the value of bat_posp_t_check_result.SA_CUSTOMER_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaCustomerFee() {
        return saCustomerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_CUSTOMER_FEE
     *
     * @param saCustomerFee the value for bat_posp_t_check_result.SA_CUSTOMER_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaCustomerFee(BigDecimal saCustomerFee) {
        this.saCustomerFee = saCustomerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.D_ERR_AMOUNT
     *
     * @return the value of bat_posp_t_check_result.D_ERR_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getdErrAmount() {
        return dErrAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.D_ERR_AMOUNT
     *
     * @param dErrAmount the value for bat_posp_t_check_result.D_ERR_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setdErrAmount(BigDecimal dErrAmount) {
        this.dErrAmount = dErrAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.C_ERR_AMOUNT
     *
     * @return the value of bat_posp_t_check_result.C_ERR_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getcErrAmount() {
        return cErrAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.C_ERR_AMOUNT
     *
     * @param cErrAmount the value for bat_posp_t_check_result.C_ERR_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setcErrAmount(BigDecimal cErrAmount) {
        this.cErrAmount = cErrAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_ACQ_BRC_FEE
     *
     * @return the value of bat_posp_t_check_result.SA_ACQ_BRC_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaAcqBrcFee() {
        return saAcqBrcFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_ACQ_BRC_FEE
     *
     * @param saAcqBrcFee the value for bat_posp_t_check_result.SA_ACQ_BRC_FEE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaAcqBrcFee(BigDecimal saAcqBrcFee) {
        this.saAcqBrcFee = saAcqBrcFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.D_FEE_AMOUNT
     *
     * @return the value of bat_posp_t_check_result.D_FEE_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getdFeeAmount() {
        return dFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.D_FEE_AMOUNT
     *
     * @param dFeeAmount the value for bat_posp_t_check_result.D_FEE_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setdFeeAmount(BigDecimal dFeeAmount) {
        this.dFeeAmount = dFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.C_FEE_AMOUNT
     *
     * @return the value of bat_posp_t_check_result.C_FEE_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getcFeeAmount() {
        return cFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.C_FEE_AMOUNT
     *
     * @param cFeeAmount the value for bat_posp_t_check_result.C_FEE_AMOUNT
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setcFeeAmount(BigDecimal cFeeAmount) {
        this.cFeeAmount = cFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SAV1
     *
     * @return the value of bat_posp_t_check_result.SA_SAV1
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaSav1() {
        return saSav1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SAV1
     *
     * @param saSav1 the value for bat_posp_t_check_result.SA_SAV1
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSav1(BigDecimal saSav1) {
        this.saSav1 = saSav1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SAV2
     *
     * @return the value of bat_posp_t_check_result.SA_SAV2
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public BigDecimal getSaSav2() {
        return saSav2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SAV2
     *
     * @param saSav2 the value for bat_posp_t_check_result.SA_SAV2
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSav2(BigDecimal saSav2) {
        this.saSav2 = saSav2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SAV3
     *
     * @return the value of bat_posp_t_check_result.SA_SAV3
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSav3() {
        return saSav3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SAV3
     *
     * @param saSav3 the value for bat_posp_t_check_result.SA_SAV3
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSav3(String saSav3) {
        this.saSav3 = saSav3 == null ? null : saSav3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SAV4
     *
     * @return the value of bat_posp_t_check_result.SA_SAV4
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSav4() {
        return saSav4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SAV4
     *
     * @param saSav4 the value for bat_posp_t_check_result.SA_SAV4
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSav4(String saSav4) {
        this.saSav4 = saSav4 == null ? null : saSav4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_SAV5
     *
     * @return the value of bat_posp_t_check_result.SA_SAV5
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaSav5() {
        return saSav5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_SAV5
     *
     * @param saSav5 the value for bat_posp_t_check_result.SA_SAV5
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaSav5(String saSav5) {
        this.saSav5 = saSav5 == null ? null : saSav5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.SA_FRNT_DATE
     *
     * @return the value of bat_posp_t_check_result.SA_FRNT_DATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getSaFrntDate() {
        return saFrntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.SA_FRNT_DATE
     *
     * @param saFrntDate the value for bat_posp_t_check_result.SA_FRNT_DATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setSaFrntDate(String saFrntDate) {
        this.saFrntDate = saFrntDate == null ? null : saFrntDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.ETLNAME
     *
     * @return the value of bat_posp_t_check_result.ETLNAME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getEtlname() {
        return etlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.ETLNAME
     *
     * @param etlname the value for bat_posp_t_check_result.ETLNAME
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setEtlname(String etlname) {
        this.etlname = etlname == null ? null : etlname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_posp_t_check_result.DATADATE
     *
     * @return the value of bat_posp_t_check_result.DATADATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public String getDatadate() {
        return datadate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_posp_t_check_result.DATADATE
     *
     * @param datadate the value for bat_posp_t_check_result.DATADATE
     *
     * @mbggenerated Wed Aug 23 16:10:54 CST 2017
     */
    public void setDatadate(String datadate) {
        this.datadate = datadate == null ? null : datadate.trim();
    }
}